RTL ?= $(abspath ../../rtl)
TOPLEVEL = poly_arith_tb
MODULE = test_poly_arith
VERILOG_SOURCES = $(abspath poly_arith_tb.sv) $(RTL)/poly_arith.sv $(RTL)/modmul.sv $(RTL)/zeta_rom.sv $(RTL)/poly_mem.sv $(RTL)/ram_tdp.sv
include ../Makefile.inc
